# pip install -r docs/requirements.txt
# mkdocs serve

site_name: GitHub Workflows Kt
site_author: Piotr Krzemiński
repo_url: https://github.com/typesafegithub/github-workflows-kt/
edit_uri: https://github.com/typesafegithub/github-workflows-kt/tree/main/docs

theme:
  logo: Logo.svg
  name: material
  features:
    - navigation.expand
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - pymdownx.magiclink
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path:
        - library/src/test/kotlin/io/github/typesafegithub/workflows/docsnippets
      check_paths: True
      dedent_subsections: True
  - admonition

plugins:
  - markdownextradata:
      jinja_options:
        variable_start_string: '[['
        variable_end_string: ']]'
  - search
  - mkdocs-video

nav:
  - Introduction: 'index.md'
  - User guide:
      - Getting started: 'user-guide/getting_started.md'
      - Script generator (experimental): 'user-guide/kotlin2yaml.md'
      - Using actions: 'user-guide/using-actions.md'
      - Type-safe expressions: 'user-guide/type-safe-expressions.md'
      - Job outputs: 'user-guide/job-outputs.md'
      - Compensating library's missing features: 'user-guide/compensating-librarys-missing-features.md'
      - Nightly builds: 'user-guide/nightly-builds.md'
  - Feature coverage: 'feature-coverage.md'
  - Supported actions: 'supported-actions.md'
  - API docs: 'https://typesafegithub.github.io/github-workflows-kt/api-docs/'
  - Projects using this library: 'projects-using-this-library.md'

extra:
  version: 0.44.0-SNAPSHOT

  # branch or tag name - the kotlin2yaml may have not yet updated to a breaking change in the library
  kotlin2yamlVersion: 0.44.0
