name: all-triggers

on:
    branch_protection_rule:
        types:
            - 'created'
            - 'deleted'
    check_run:
        types:
            - 'completed'
            - 'rerequested'
    check_suite:
    create:
    delete:
    deployment:
    deployment_status:
    discussion:
        types:
            - 'created'
            - 'edited'
            - 'answered'
    discussion_comment:
    fork:
    gollum:
    issue_comment:
        types:
            - 'created'
            - 'edited'
            - 'deleted'
    issues:
        types:
            - 'opened'
            - 'edited'
    label:
        types:
            - 'crDiscussionCommenteated'
            - 'deleted'
            - 'edited'
    milestone:
        types:
            - 'created'
            - 'closed'
    page_build:
    project:
        types:
            - 'created'
            - 'deleted'
    project_card:
        types:
            - 'created'
            - 'moved'
    project_column:
        types:
            - 'moved'
    public:
    pull_request:
    pull_request_review:
    pull_request_review_comment:
        types:
            - 'created'
            - 'edited'
    pull_request_target:
    push:
    registry_package:
        types:
            - 'published'
            - 'updated'
    release:
        types:
            - 'published'
            - 'unpublished'
    repository_dispatch:
    schedule:
        - cron: "* * * * *"
    status:
        types:
            - 'started'
    watch:
    workflow_call:
    workflow_dispatch:
    workflow_run:
        types:
            - 'completed'
            - 'requested'
jobs:
    "job-0":
        runs-on: "ubuntu-latest"
        steps:
            -   id: step-0
                name: Check out
                uses: actions/checkout@v3
