name: RefreshVersions Pr

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * 1'

jobs:
  "Refresh-Versions":
    runs-on: "ubuntu-latest"
    steps:
      - name: check-out
        uses: actions/checkout@v3
        with:
          ref: main
      - name: setup-java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt
      - name: create-branch
        uses: peterjgrainger/action-create-branch@v2.1.0
        with:
          branch: dependency-update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: gradle refreshVersions
        uses: gradle/gradle-build-action@v2
        with:
          arguments: refreshVersions
      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: noreply@github.com
          message: Refresh versions.properties
          new_branch: dependency-update
          push: --force --set-upstream origin dependency-update
      - name: Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: dependency-update
          destination_branch: main
          pr_title: Upgrade gradle dependencies
          pr_body: '[refreshVersions](https://github.com/jmfayard/refreshVersions) has found those library updates!'
          pr_draft: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
